# Werkzeuge fuer dieses Projekt. Installieren mit: rokit install
[tools]
rojo = "rojo-rbx/rojo@7.7.1"
selene = "Kampfkarren/selene@0.31.0"
stylua = "JohnnyMorganz/StyLua@2.5.2"
lune = "lune-org/lune@0.10.4" # automatische Tests: lune run tests/run
